<?php
/**
 * @file
 * Code for the Conzultrix User feature.
 */

include_once 'conzultrix_user.features.inc';
module_load_include('inc', 'conzultrix_user', 'conzultrix_user.block');

function conzultrix_user_preprocess_username(&$variables) {
  // Ensure that the full user object is loaded.
  $account = user_load($variables['account']->uid);

  // See there first_name and last_name fields and add that as the name instead.

  
  if (isset($account->field_first_name[LANGUAGE_NONE][0]['safe_value']) && isset($account->field_last_name[LANGUAGE_NONE][0]['safe_value'])) {
    $fullname = $account->field_first_name[LANGUAGE_NONE][0]['safe_value'] . " " . $account->field_last_name[LANGUAGE_NONE][0]['safe_value'];
    
    // Shorten the fullname when it is too long or it will break many tables.
    if (drupal_strlen($fullname) > 20) {
      $fullname = drupal_substr($fullname, 0, 15) .'...';
    }
    $variables['name'] = $fullname;
  }
  
}


/**
 * Implements hook_menu_alter().
 */
function conzultrix_user_menu_alter(&$items) {
  $items['user/%user']['title callback'] = 'conzultrix_user_page_title';
  
  if (user_is_anonymous()) {
    $items['user/login']['title callback'] = 'drupal_set_title';
    $items['user/login']['title arguments'] = array('Sign In');
  }
  
  // remove tabs from login page and change them to links;
  $items['user']['type'] = MENU_CALLBACK;
  $items['user/password']['type'] = MENU_CALLBACK;
	$items['user/register']['type'] = MENU_CALLBACK;
}

function conzultrix_user_page_title() {
  if (arg(0) == 'user') {
    // load uid from url
    $user = user_load(arg(1));
    if (isset($user->field_first_name[LANGUAGE_NONE][0]['safe_value']) && isset($user->field_last_name[LANGUAGE_NONE][0]['safe_value'])) {
      $fullname = $user->field_first_name[LANGUAGE_NONE][0]['safe_value'] . ' ' . $user->field_last_name[LANGUAGE_NONE][0]['safe_value'];
    }
  }
  // fallback to username if custom fields are not set.
  if (empty($fullname)) {
    $fullname = $user->name;
  }
  
  return $fullname;
}

/**
 * Implements hook_block_info().
 */
function conzultrix_user_block_info() {
  // create the user information block
  // to include photo and other info 
  $blocks['conzultrix_user_info'] = array(
    'info' => t('Conzultrix User Info'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['login_intro'] = array(
    'info' => t('Login Inrto'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function conzultrix_user_block_view($delta = '') {
  $block = array();
  
  switch ($delta) {
    
    case 'conzultrix_user_info' :
      $content = conzultrix_user_user_info_block();
      if (!empty($content)) {
        $block['subject'] = t('');
        $block['content'] = $content;
      }
      break;
    
    case 'login_intro' :
      $block['subject'] = t('');
      $block['content'] = '<div class="login-intro"><h2>Conzultrix</h2><div class="login-caption">Make Impact</div></div>';
      break;
  }
  
  return $block;
}