<?php
/**
 * @file
 * Drupal needs this blank file.
 */

 /**
 * Implements hook_form_FORM_ID_alter().
 */
function conzultrix_contact_form_contact_site_form_alter(&$form, &$form_state) { 
  // Add an optional textfield to collect
  // users phone number in the contact form
  $form['phone'] = array(
    '#title' => t('Phone'),
    '#type' => 'textfield',
  );
  
  // resort the form so that the phone number is
  // at the right spot
  
  $order = array(
    'name',
    'mail',
    'phone',
    'subject',
    'cid',
    'message',
    'copy',
    'submit',
  );
  
  foreach ($order as $key => $field) {
    // set/reset the field's weight to the
    // array key value from the order array
    $form[$field]['#weight'] = $key;
  }
  
  // for default category hide the
  // category select field if contact_forms
  // module is enabled
  if (module_exists('contact_forms')) {
    //$path = current_path();
    if (current_path() == 'contact') {
      $form['cid']['#type'] = 'hidden';
      $form['cid']['#value'] = $form['cid']['#default_value'];
    }
  }
}

/**
 * Implements hook_mail_alter().
 */
function conzultrix_contact_mail_alter(&$message) {
  // We only want to alter the email if it's being
  // sent by the site-wide contact form page/
  if ($message['id'] == 'contact_page_mail' || 'contact_page_copy') {
    $message['body'][] = t('Phone') . ': ' . $message['params']['phone'];
  }
}